# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "senotrusov-ruby-toolkit"
  s.version = "1.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stanislav Senotrusov"]
  s.date = "2012-06-03"
  s.email = "stan@senotrusov.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "lib.outdated/accessors_generator.rb",
    "lib.outdated/actionpack/action_controller_skip_render.rb",
    "lib.outdated/actionpack/action_view_select_helpers.rb",
    "lib.outdated/actionpack/graphviz_filter.rb",
    "lib.outdated/actionpack/prototype_helper_javascript_generator.rb",
    "lib.outdated/actionpack/summary_table.rb",
    "lib.outdated/actionpack/to_textile.rb",
    "lib.outdated/actionpack/truefalsize_checkbox.rb",
    "lib.outdated/activerecord/abstract_adapter_connection_title.rb",
    "lib.outdated/activerecord/acts_as_scope_restricted.rb",
    "lib.outdated/activerecord/acts_as_sometimes_active.rb",
    "lib.outdated/activerecord/cached_config.rb",
    "lib.outdated/activerecord/conditions_builder.rb",
    "lib.outdated/activerecord/constant_accessor.rb",
    "lib.outdated/activerecord/force_reload_all_associated.rb",
    "lib.outdated/activerecord/marshaled_attr.rb",
    "lib.outdated/activerecord/postgresql_notifications.rb",
    "lib.outdated/activerecord/sanitize_sql.rb",
    "lib.outdated/activerecord/subclasses.rb",
    "lib.outdated/activerecord/touch.rb",
    "lib.outdated/activerecord/transaction_mutex.rb",
    "lib.outdated/check_is_active.rb",
    "lib.outdated/regexp_russian_ignore_case.rb",
    "lib/ruby-senotrusov-toolkit.rb",
    "lib/ruby-senotrusov-toolkit/actionpack/routes_regexp_constrain_with_formats.rb",
    "lib/ruby-senotrusov-toolkit/actionpack/stan_application_helper.rb",
    "lib/ruby-senotrusov-toolkit/activerecord/if-unless-also.rb",
    "lib/ruby-senotrusov-toolkit/activerecord/normalize.rb",
    "lib/ruby-senotrusov-toolkit/activerecord/postgresql_exec.rb",
    "lib/ruby-senotrusov-toolkit/activerecord/presentation.rb",
    "lib/ruby-senotrusov-toolkit/base62.rb",
    "lib/ruby-senotrusov-toolkit/sequence.rb",
    "lib/ruby-senotrusov-toolkit/string/equal_sized_chunks.rb",
    "lib/ruby-senotrusov-toolkit/string/gsubh.rb",
    "lib/ruby-senotrusov-toolkit/string/isascii.rb",
    "lib/ruby-senotrusov-toolkit/string/squeeze_more.rb",
    "lib/ruby-senotrusov-toolkit/string/to_hex_bin_view.rb",
    "lib/ruby-senotrusov-toolkit/thread/threadsafe_sequence.rb",
    "lib/ruby-senotrusov-toolkit/thread/threadsafe_sequence_loop.rb",
    "snippets/rails.rb",
    "vendor/assets/images/loading-block-slow.gif",
    "vendor/assets/images/loading-optimized-fast.gif",
    "vendor/assets/images/loading-optimized.gif",
    "vendor/assets/images/loading-slow.gif",
    "vendor/assets/images/loading.gif",
    "vendor/loading-corners.xcf",
    "vendor/loading.xcf"
  ]
  s.homepage = "http://github.com/senotrusov/senotrusov-ruby-toolkit"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Helpers for my ruby applications"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 0"])
  end
end

