# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "stan-ruby-toolkit"
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stanislav Senotrusov"]
  s.date = "2012-06-04"
  s.email = "stan@senotrusov.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "snippets/rails.rb",
    "vendor/assets/images/loading-block-slow.gif",
    "vendor/assets/images/loading-optimized-fast.gif",
    "vendor/assets/images/loading-optimized.gif",
    "vendor/assets/images/loading-slow.gif",
    "vendor/assets/images/loading.gif",
    "vendor/loading-corners.xcf",
    "vendor/loading.xcf"
  ]
  s.homepage = "http://github.com/senotrusov/stan-ruby-toolkit"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Helpers for my ruby applications"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 0"])
  end
end

